from typing import Protocol
from uuid import UUID

from modules.campaigns.domain.entities import Campaign
from shared.enums import Perfil


class CampaignRepository(Protocol):
    def get(self, campaign_id: UUID) -> Campaign | None: ...
    def list_all(self) -> list[Campaign]: ...
    def list_for_perfil(self, perfil: Perfil) -> list[Campaign]: ...
    def add(self, campaign: Campaign) -> Campaign: ...
    def count_submissions(self, campaign_id: UUID) -> int: ...
