version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_prod
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend