from typing import Protocol
from uuid import UUID

from modules.identity.domain.entities import User
from shared.enums import Perfil


class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> User | None: ...
    def get_by_identificador(self, identificador: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def count_by_perfis(self, perfis: list[Perfil]) -> int: ...
    def list_by_perfis(self, perfis: list[Perfil]) -> list[User]: ...


class PasswordHasher(Protocol):
    def hash(self, senha: str) -> str: ...
    def verify(self, senha: str, senha_hash: str) -> bool: ...
