from typing import Protocol
from uuid import UUID

from modules.questionnaires.domain.entities import Questionnaire


class QuestionnaireRepository(Protocol):
    def get(self, questionnaire_id: UUID) -> Questionnaire | None: ...
    def list_all(self) -> list[Questionnaire]: ...
    def add(self, questionnaire: Questionnaire) -> Questionnaire: ...
    def has_submissions(self, questionnaire_id: UUID) -> bool: ...
    def count_usos(self, questionnaire_id: UUID) -> int: ...
