from typing import Protocol
from uuid import UUID

from modules.responses.domain.entities import Participation, Submission


class ParticipationRepository(Protocol):
    def exists(self, user_id: UUID, campaign_id: UUID) -> bool: ...
    def add(self, participation: Participation) -> Participation: ...
    def list_by_user(self, user_id: UUID) -> list[Participation]: ...
    def get(self, user_id: UUID, campaign_id: UUID) -> Participation | None: ...


class SubmissionRepository(Protocol):
    def add(self, submission: Submission) -> Submission: ...
    def list_by_campaign(self, campaign_id: UUID) -> list[Submission]: ...
    def list_all(self) -> list[Submission]: ...
