name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar pytest
        run: pytest

  build-backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Build Backend (Dev)
        run: docker build -f backend/Dockerfile.dev ./backend

      - name: Build Backend (Prod)
        run: docker build -f backend/Dockerfile ./backend

  
  build-frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Build Frontend (Dev)
        run: docker build -f frontend/Dockerfile.dev ./frontend

      - name: Build Frontend (Prod)
        run: docker build -f frontend/Dockerfile ./frontend